safe: false
lsi: false
pygments: true
markdown: redcarpet
baseurl: /hyperagent/

navigation:
- text: API
  url: /index.html
  link: /
- text: Contributing
  url: /contributing/index.html
  link: /contributing
